import React from "react";
import Head from "next/head";
import airplane from "../public/img/airplane.svg";
import Image from "next/image";
import Link from "next/link";
import { Form } from "../components/contact/Form";
import { motion } from "framer-motion";
import { NavBar } from "../components/navBar";

export default function contato() {
  return (
    <div>
      <Head>
        <title>Portfolio - Matheus Borges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center h-screen relative">
        <motion.h1
          initial={{ opacity: 0, x: -50 }}
          whileInView={{ opacity: 1, x: 0 }}
          transition={{
            type: "spring",
            stiffness: 120,
            damping: 20,
            staggerChildren: 0.3,
          }}
          className="text-gray text-2xl font-medium uppercase absolute top-5 left-4"
        >
          <span className="text-roxo text-2xl font-bold"> | </span>
          Contato
        </motion.h1>

        <Link
          href="/"
          className="text-roxo text-base font-medium uppercase absolute top-14 left-4"
        >
          ← voltar
        </Link>

        <div className="flex flex-col justify-center items-center p-3">
          <motion.div
            initial={{ opacity: 0, x: -100, y: 100 }}
            whileInView={{ opacity: 1, x: 0, y: 0 }}
            transition={{
              type: "spring",
              stiffness: 80,
              damping: 20,
              staggerChildren: 0.5,
              delay: 0.5,
            }}
          >
            <Image
              src={airplane}
              id="color"
              className="w-12 md:w-14"
              draggable="false"
              alt="airplane"
            />
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{
              type: "spring",
              stiffness: 80,
              damping: 20,
              delay: 1.7,
            }}
            className="flex justify-center items-center mt-2"
          >
            <Form />
          </motion.div>
        </div>
      </main>
    </div>
  );
}
