import React from "react";
import { motion } from "framer-motion";
import { Form } from "../components/Contact/Form";
import Head from "next/head";
import airplane from "../public/img/airplane.svg";
import Image from "next/image";
import Link from "next/link";
import Back from "../public/img/BackArrow.svg";

export default function contato() {
  return (
    <div>
      <Head>
        <title>Portfolio - Matheus Borges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center h-screen relative">
        <Link href="/" className="text-roxo absolute top-5 left-4">
          <Image src={Back} className="w-16" draggable="false" alt="Voltar" />
        </Link>

        <div className="flex flex-col justify-center items-center p-3">
          <motion.div
            initial={{ opacity: 0, x: -100, y: 100 }}
            whileInView={{ opacity: 1, x: 0, y: 0 }}
            transition={{
              type: "spring",
              stiffness: 80,
              damping: 20,
              staggerChildren: 0.5,
              delay: 0.5,
            }}
          >
            <Image
              src={airplane}
              id="color"
              className="w-12"
              draggable="false"
              alt="airplane"
            />
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{
              type: "spring",
              stiffness: 80,
              damping: 20,
              delay: 1.5,
            }}
            className="flex justify-center items-center mt-2"
          >
            <Form />
          </motion.div>
        </div>
      </main>
    </div>
  );
}
