import Head from "next/head";
import useScrollSnap from "react-use-scroll-snap";
import React, { useRef } from "react";
import { Presentation } from "../components/Presentation";
import { Skills } from "../components/Skills/Skills";
import { Contact } from "../components/Contact/Contact";
import { Footer } from "../components/Footer";
import { Education } from "../components/Education";
import { motion, useScroll } from "framer-motion";
import { Certificates } from "../components/Certificate/Certificates";

export default function Home() {
  const scrollRef = useRef(null);
  useScrollSnap({ ref: scrollRef, duration: 10, delay: 0 });

  const { scrollYProgress } = useScroll();

  return (
    <div>
      <Head>
        <title>Portfolio - Matheus Borges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div
        className="progress-bar"
        style={{ scaleX: scrollYProgress }}
      />

      <main ref={scrollRef}>
        <section className="flex flex-col justify-center h-screen bg-home">
          <Presentation />
        </section>

        <section className="flex justify-center h-screen bg-home">
          <Skills />
        </section>

        <section className="flex justify-center h-screen bg-home">
          <Education />
        </section>

        <section className="flex justify-center h-screen bg-home">
          <Certificates />
        </section>

        <section id="contact" className="flex justify-center h-screen bg-home">
          <Contact />
        </section>
      </main>

      <Footer />
    </div>
  );
}
