import Head from "next/head";
import { motion } from "framer-motion";
import { Nav } from "../components/Nav";
import { Project } from "../components/Project";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio - Matheus Borges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;800&display=swap"
        />
      </Head>

      <section className="flex flex-col justify-center h-screen bg-home">
        <div className="flex items-center justify-center absolute top-0 mb-5">
          <Nav />
        </div>

        <Project />
      </section>
    </div>
  );
}
