import Head from "next/head";
import { motion } from "framer-motion";
import { Nav } from "../components/Nav";
import { Project } from "../components/Projects/Project";
import { Inter } from "@next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

export default function Home() {
  return (
    <div className={inter.className}>
      <Head>
        <title>Portfolio - Matheus Borges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex flex-col justify-center h-screen bg-home">
        <div className="flex items-center justify-center absolute top-0 mb-5">
          <Nav />
        </div>

        <Project />
      </section>
    </div>
  );
}
