import Head from "next/head";
import { motion } from "framer-motion";
import { Nav } from "../components/Nav";
import { Project } from "../components/Project";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio - Matheus Borges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;800&display=swap"
        />
      </Head>

      <div className="bg-home h-screen">
        <div className="flex justify-center items-center">
          <Nav />
        </div>

        <div data-aos="zoom-in-up" className="mt-6">
          <Project />
        </div>
      </div>
    </div>
  );
}
